[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
libs = ["contracts/lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Remappings so imports like `@openzeppelin/...` and `forge-std/...` resolve from repo root
remappings = [
	"@openzeppelin/=contracts/lib/openzeppelin-contracts/",
	"forge-std/=contracts/lib/forge-std/src/"
]

# Ignore third-party library test and certora folders so Foundry doesn't try to compile them
ignored_paths = [
	"contracts/lib/openzeppelin-contracts/test",
	"contracts/lib/openzeppelin-contracts/certora",
	"contracts/lib/openzeppelin-contracts/lib/erc4626-tests"
]

# Keep the same RPC and etherscan config optional; inherited from contracts config if running there
